# Generated by Django 3.2.12 on 2022-03-31 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220324_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.forumuser')),
            ],
        ),
        migrations.CreateModel(
            name='PostDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.forumuser')),
            ],
        ),
    ]
